import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../generated/prisma/client";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

// ─── Teams ────────────────────────────────────────────────────────────────────

const teams = [
  // Grupo A
  { name: "Qatar",         code: "QAT", flagEmoji: "🇶🇦", groupLetter: "A" },
  { name: "Ecuador",       code: "ECU", flagEmoji: "🇪🇨", groupLetter: "A" },
  { name: "Senegal",       code: "SEN", flagEmoji: "🇸🇳", groupLetter: "A" },
  { name: "Países Bajos",  code: "NED", flagEmoji: "🇳🇱", groupLetter: "A" },
  // Grupo B
  { name: "Inglaterra",    code: "ENG", flagEmoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", groupLetter: "B" },
  { name: "Irán",          code: "IRN", flagEmoji: "🇮🇷", groupLetter: "B" },
  { name: "Estados Unidos",code: "USA", flagEmoji: "🇺🇸", groupLetter: "B" },
  { name: "Gales",         code: "WAL", flagEmoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", groupLetter: "B" },
  // Grupo C
  { name: "Argentina",     code: "ARG", flagEmoji: "🇦🇷", groupLetter: "C" },
  { name: "Arabia Saudita",code: "KSA", flagEmoji: "🇸🇦", groupLetter: "C" },
  { name: "México",        code: "MEX", flagEmoji: "🇲🇽", groupLetter: "C" },
  { name: "Polonia",       code: "POL", flagEmoji: "🇵🇱", groupLetter: "C" },
  // Grupo D
  { name: "Francia",       code: "FRA", flagEmoji: "🇫🇷", groupLetter: "D" },
  { name: "Australia",     code: "AUS", flagEmoji: "🇦🇺", groupLetter: "D" },
  { name: "Dinamarca",     code: "DEN", flagEmoji: "🇩🇰", groupLetter: "D" },
  { name: "Túnez",         code: "TUN", flagEmoji: "🇹🇳", groupLetter: "D" },
  // Grupo E
  { name: "España",        code: "ESP", flagEmoji: "🇪🇸", groupLetter: "E" },
  { name: "Costa Rica",    code: "CRC", flagEmoji: "🇨🇷", groupLetter: "E" },
  { name: "Alemania",      code: "GER", flagEmoji: "🇩🇪", groupLetter: "E" },
  { name: "Japón",         code: "JPN", flagEmoji: "🇯🇵", groupLetter: "E" },
  // Grupo F
  { name: "Bélgica",       code: "BEL", flagEmoji: "🇧🇪", groupLetter: "F" },
  { name: "Canadá",        code: "CAN", flagEmoji: "🇨🇦", groupLetter: "F" },
  { name: "Marruecos",     code: "MAR", flagEmoji: "🇲🇦", groupLetter: "F" },
  { name: "Croacia",       code: "CRO", flagEmoji: "🇭🇷", groupLetter: "F" },
  // Grupo G
  { name: "Brasil",        code: "BRA", flagEmoji: "🇧🇷", groupLetter: "G" },
  { name: "Serbia",        code: "SRB", flagEmoji: "🇷🇸", groupLetter: "G" },
  { name: "Suiza",         code: "SUI", flagEmoji: "🇨🇭", groupLetter: "G" },
  { name: "Camerún",       code: "CMR", flagEmoji: "🇨🇲", groupLetter: "G" },
  // Grupo H
  { name: "Portugal",      code: "POR", flagEmoji: "🇵🇹", groupLetter: "H" },
  { name: "Ghana",         code: "GHA", flagEmoji: "🇬🇭", groupLetter: "H" },
  { name: "Uruguay",       code: "URU", flagEmoji: "🇺🇾", groupLetter: "H" },
  { name: "Corea del Sur", code: "KOR", flagEmoji: "🇰🇷", groupLetter: "H" },
];

async function seedTeams() {
  const { count } = await prisma.team.createMany({ data: teams, skipDuplicates: true });
  console.log(count > 0 ? `✓ ${count} equipos insertados.` : "Seed omitido: equipos ya existentes.");
}

// ─── Matches ──────────────────────────────────────────────────────────────────

async function seedMatches() {
  const teamRows = await prisma.team.findMany({ select: { id: true, code: true } });
  const codeToId = Object.fromEntries(teamRows.map((t) => [t.code, t.id]));

  const matches = [
    // ── Fecha 1 ────────────────────────────────────────────────────────────────
    { home: "QAT", away: "ECU", group: "A", utc: "2022-11-20T16:00:00Z", stadium: "Al Bayt Stadium" },
    { home: "ENG", away: "IRN", group: "B", utc: "2022-11-21T13:00:00Z", stadium: "Khalifa International Stadium" },
    { home: "SEN", away: "NED", group: "A", utc: "2022-11-21T16:00:00Z", stadium: "Al Thumama Stadium" },
    { home: "USA", away: "WAL", group: "B", utc: "2022-11-21T19:00:00Z", stadium: "Ahmad Bin Ali Stadium" },
    { home: "ARG", away: "KSA", group: "C", utc: "2022-11-22T10:00:00Z", stadium: "Lusail Stadium" },
    { home: "DEN", away: "TUN", group: "D", utc: "2022-11-22T13:00:00Z", stadium: "Education City Stadium" },
    { home: "MEX", away: "POL", group: "C", utc: "2022-11-22T16:00:00Z", stadium: "Stadium 974" },
    { home: "FRA", away: "AUS", group: "D", utc: "2022-11-22T19:00:00Z", stadium: "Al Janoub Stadium" },
    { home: "MAR", away: "CRO", group: "F", utc: "2022-11-23T10:00:00Z", stadium: "Al Bayt Stadium" },
    { home: "GER", away: "JPN", group: "E", utc: "2022-11-23T13:00:00Z", stadium: "Khalifa International Stadium" },
    { home: "ESP", away: "CRC", group: "E", utc: "2022-11-23T16:00:00Z", stadium: "Al Thumama Stadium" },
    { home: "BEL", away: "CAN", group: "F", utc: "2022-11-23T19:00:00Z", stadium: "Ahmad Bin Ali Stadium" },
    { home: "SUI", away: "CMR", group: "G", utc: "2022-11-24T10:00:00Z", stadium: "Al Janoub Stadium" },
    { home: "URU", away: "KOR", group: "H", utc: "2022-11-24T13:00:00Z", stadium: "Education City Stadium" },
    { home: "POR", away: "GHA", group: "H", utc: "2022-11-24T16:00:00Z", stadium: "Stadium 974" },
    { home: "BRA", away: "SRB", group: "G", utc: "2022-11-24T19:00:00Z", stadium: "Lusail Stadium" },
    // ── Fecha 2 ────────────────────────────────────────────────────────────────
    { home: "WAL", away: "IRN", group: "B", utc: "2022-11-25T10:00:00Z", stadium: "Ahmad Bin Ali Stadium" },
    { home: "QAT", away: "SEN", group: "A", utc: "2022-11-25T13:00:00Z", stadium: "Al Thumama Stadium" },
    { home: "NED", away: "ECU", group: "A", utc: "2022-11-25T16:00:00Z", stadium: "Khalifa International Stadium" },
    { home: "ENG", away: "USA", group: "B", utc: "2022-11-25T19:00:00Z", stadium: "Al Bayt Stadium" },
    { home: "TUN", away: "AUS", group: "D", utc: "2022-11-26T10:00:00Z", stadium: "Al Janoub Stadium" },
    { home: "POL", away: "KSA", group: "C", utc: "2022-11-26T13:00:00Z", stadium: "Education City Stadium" },
    { home: "FRA", away: "DEN", group: "D", utc: "2022-11-26T16:00:00Z", stadium: "Stadium 974" },
    { home: "ARG", away: "MEX", group: "C", utc: "2022-11-26T19:00:00Z", stadium: "Lusail Stadium" },
    { home: "JPN", away: "CRC", group: "E", utc: "2022-11-27T10:00:00Z", stadium: "Ahmad Bin Ali Stadium" },
    { home: "BEL", away: "MAR", group: "F", utc: "2022-11-27T13:00:00Z", stadium: "Al Thumama Stadium" },
    { home: "CRO", away: "CAN", group: "F", utc: "2022-11-27T16:00:00Z", stadium: "Khalifa International Stadium" },
    { home: "ESP", away: "GER", group: "E", utc: "2022-11-27T19:00:00Z", stadium: "Al Bayt Stadium" },
    { home: "CMR", away: "SRB", group: "G", utc: "2022-11-28T10:00:00Z", stadium: "Al Janoub Stadium" },
    { home: "KOR", away: "GHA", group: "H", utc: "2022-11-28T13:00:00Z", stadium: "Education City Stadium" },
    { home: "BRA", away: "SUI", group: "G", utc: "2022-11-28T16:00:00Z", stadium: "Stadium 974" },
    { home: "POR", away: "URU", group: "H", utc: "2022-11-28T19:00:00Z", stadium: "Lusail Stadium" },
    // ── Fecha 3 (simultáneos por grupo) ───────────────────────────────────────
    { home: "NED", away: "QAT", group: "A", utc: "2022-11-29T15:00:00Z", stadium: "Al Bayt Stadium" },
    { home: "ECU", away: "SEN", group: "A", utc: "2022-11-29T15:00:00Z", stadium: "Khalifa International Stadium" },
    { home: "WAL", away: "ENG", group: "B", utc: "2022-11-29T19:00:00Z", stadium: "Ahmad Bin Ali Stadium" },
    { home: "IRN", away: "USA", group: "B", utc: "2022-11-29T19:00:00Z", stadium: "Al Thumama Stadium" },
    { home: "AUS", away: "DEN", group: "D", utc: "2022-11-30T15:00:00Z", stadium: "Al Janoub Stadium" },
    { home: "TUN", away: "FRA", group: "D", utc: "2022-11-30T15:00:00Z", stadium: "Education City Stadium" },
    { home: "POL", away: "ARG", group: "C", utc: "2022-11-30T19:00:00Z", stadium: "Stadium 974" },
    { home: "KSA", away: "MEX", group: "C", utc: "2022-11-30T19:00:00Z", stadium: "Lusail Stadium" },
    { home: "CRO", away: "BEL", group: "F", utc: "2022-12-01T15:00:00Z", stadium: "Ahmad Bin Ali Stadium" },
    { home: "CAN", away: "MAR", group: "F", utc: "2022-12-01T15:00:00Z", stadium: "Al Thumama Stadium" },
    { home: "JPN", away: "ESP", group: "E", utc: "2022-12-01T19:00:00Z", stadium: "Khalifa International Stadium" },
    { home: "CRC", away: "GER", group: "E", utc: "2022-12-01T19:00:00Z", stadium: "Al Bayt Stadium" },
    { home: "KOR", away: "POR", group: "H", utc: "2022-12-02T15:00:00Z", stadium: "Education City Stadium" },
    { home: "GHA", away: "URU", group: "H", utc: "2022-12-02T15:00:00Z", stadium: "Al Janoub Stadium" },
    { home: "CMR", away: "BRA", group: "G", utc: "2022-12-02T19:00:00Z", stadium: "Lusail Stadium" },
    { home: "SRB", away: "SUI", group: "G", utc: "2022-12-02T19:00:00Z", stadium: "Stadium 974" },
  ];

  const data = matches.map((m) => ({
    round: "group",
    homeTeamId: codeToId[m.home],
    awayTeamId: codeToId[m.away],
    groupLetter: m.group,
    scheduledAtUtc: new Date(m.utc),
    stadium: m.stadium,
  }));

  const { count } = await prisma.match.createMany({ data, skipDuplicates: true });
  console.log(count > 0 ? `✓ ${count} partidos insertados.` : "Seed omitido: partidos ya existentes.");
}

// ─── Players data ────────────────────────────────────────────────────────────

const players: { teamCode: string; number: number; name: string }[] = [
  // QAT — Grupo A (26)
  { teamCode: "QAT", number: 1,  name: "Saad Al Sheeb" },
  { teamCode: "QAT", number: 2,  name: "Pedro Miguel" },
  { teamCode: "QAT", number: 3,  name: "Abdelkarim Hassan" },
  { teamCode: "QAT", number: 4,  name: "Mohammed Waad" },
  { teamCode: "QAT", number: 5,  name: "Tarek Salman" },
  { teamCode: "QAT", number: 6,  name: "Abdulaziz Hatem" },
  { teamCode: "QAT", number: 7,  name: "Ahmed Alaaeldin" },
  { teamCode: "QAT", number: 8,  name: "Ali Assadalla" },
  { teamCode: "QAT", number: 9,  name: "Mohammed Muntari" },
  { teamCode: "QAT", number: 10, name: "Hassan Al-Haydos" },
  { teamCode: "QAT", number: 11, name: "Akram Afif" },
  { teamCode: "QAT", number: 12, name: "Karim Boudiaf" },
  { teamCode: "QAT", number: 13, name: "Musab Kheder" },
  { teamCode: "QAT", number: 14, name: "Homam Ahmed" },
  { teamCode: "QAT", number: 15, name: "Bassam Al-Rawi" },
  { teamCode: "QAT", number: 16, name: "Boualem Khoukhi" },
  { teamCode: "QAT", number: 17, name: "Ismaeel Mohammad" },
  { teamCode: "QAT", number: 18, name: "Khalid Muneer" },
  { teamCode: "QAT", number: 19, name: "Almoez Ali" },
  { teamCode: "QAT", number: 20, name: "Salem Al-Hajri" },
  { teamCode: "QAT", number: 21, name: "Yousef Hassan" },
  { teamCode: "QAT", number: 22, name: "Meshaal Barsham" },
  { teamCode: "QAT", number: 23, name: "Assim Madibo" },
  { teamCode: "QAT", number: 24, name: "Naif Al-Hadhrami" },
  { teamCode: "QAT", number: 25, name: "Jassem Gaber" },
  { teamCode: "QAT", number: 26, name: "Mostafa Meshaal" },
  // ECU — Grupo A (26)
  { teamCode: "ECU", number: 1,  name: "Hernán Galíndez" },
  { teamCode: "ECU", number: 2,  name: "Félix Torres" },
  { teamCode: "ECU", number: 3,  name: "Piero Hincapié" },
  { teamCode: "ECU", number: 4,  name: "Robert Arboleda" },
  { teamCode: "ECU", number: 5,  name: "José Cifuentes" },
  { teamCode: "ECU", number: 6,  name: "Willian Pacho" },
  { teamCode: "ECU", number: 7,  name: "Pervis Estupiñán" },
  { teamCode: "ECU", number: 8,  name: "Carlos Gruezo" },
  { teamCode: "ECU", number: 9,  name: "Ayrton Preciado" },
  { teamCode: "ECU", number: 10, name: "Romario Ibarra" },
  { teamCode: "ECU", number: 11, name: "Michael Estrada" },
  { teamCode: "ECU", number: 12, name: "Moisés Ramírez" },
  { teamCode: "ECU", number: 13, name: "Enner Valencia" },
  { teamCode: "ECU", number: 14, name: "Xavier Arreaga" },
  { teamCode: "ECU", number: 15, name: "Ángel Mena" },
  { teamCode: "ECU", number: 16, name: "Jeremy Sarmiento" },
  { teamCode: "ECU", number: 17, name: "Ángelo Preciado" },
  { teamCode: "ECU", number: 18, name: "Diego Palacios" },
  { teamCode: "ECU", number: 19, name: "Gonzalo Plata" },
  { teamCode: "ECU", number: 20, name: "Sebas Méndez" },
  { teamCode: "ECU", number: 21, name: "Alan Franco" },
  { teamCode: "ECU", number: 22, name: "Alexander Domínguez" },
  { teamCode: "ECU", number: 23, name: "Moisés Caicedo" },
  { teamCode: "ECU", number: 24, name: "Djorkaeff Reasco" },
  { teamCode: "ECU", number: 25, name: "Jackson Porozo" },
  { teamCode: "ECU", number: 26, name: "Kevin Rodríguez" },
  // NED — Grupo A (26)
  { teamCode: "NED", number: 1,  name: "Remko Pasveer" },
  { teamCode: "NED", number: 2,  name: "Jurriën Timber" },
  { teamCode: "NED", number: 3,  name: "Matthijs de Ligt" },
  { teamCode: "NED", number: 4,  name: "Virgil van Dijk" },
  { teamCode: "NED", number: 5,  name: "Nathan Aké" },
  { teamCode: "NED", number: 6,  name: "Stefan de Vrij" },
  { teamCode: "NED", number: 7,  name: "Steven Bergwijn" },
  { teamCode: "NED", number: 8,  name: "Cody Gakpo" },
  { teamCode: "NED", number: 9,  name: "Luuk de Jong" },
  { teamCode: "NED", number: 10, name: "Memphis Depay" },
  { teamCode: "NED", number: 11, name: "Steven Berghuis" },
  { teamCode: "NED", number: 12, name: "Noa Lang" },
  { teamCode: "NED", number: 13, name: "Justin Bijlow" },
  { teamCode: "NED", number: 14, name: "Davy Klaassen" },
  { teamCode: "NED", number: 15, name: "Marten de Roon" },
  { teamCode: "NED", number: 16, name: "Tyrell Malacia" },
  { teamCode: "NED", number: 17, name: "Daley Blind" },
  { teamCode: "NED", number: 18, name: "Vincent Janssen" },
  { teamCode: "NED", number: 19, name: "Wout Weghorst" },
  { teamCode: "NED", number: 20, name: "Teun Koopmeiners" },
  { teamCode: "NED", number: 21, name: "Frenkie de Jong" },
  { teamCode: "NED", number: 22, name: "Denzel Dumfries" },
  { teamCode: "NED", number: 23, name: "Andries Noppert" },
  { teamCode: "NED", number: 24, name: "Kenneth Taylor" },
  { teamCode: "NED", number: 25, name: "Xavi Simons" },
  { teamCode: "NED", number: 26, name: "Jeremie Frimpong" },
  // SEN — Grupo A (26)
  { teamCode: "SEN", number: 1,  name: "Édouard Mendy" },
  { teamCode: "SEN", number: 2,  name: "Formose Mendy" },
  { teamCode: "SEN", number: 3,  name: "Kalidou Koulibaly" },
  { teamCode: "SEN", number: 4,  name: "Pape Abou Cissé" },
  { teamCode: "SEN", number: 5,  name: "Idrissa Gueye" },
  { teamCode: "SEN", number: 6,  name: "Nampalys Mendy" },
  { teamCode: "SEN", number: 7,  name: "Nicolas Jackson" },
  { teamCode: "SEN", number: 8,  name: "Cheikhou Kouyaté" },
  { teamCode: "SEN", number: 9,  name: "Boulaye Dia" },
  { teamCode: "SEN", number: 10, name: "Moussa N'Diaye" },
  { teamCode: "SEN", number: 11, name: "Pathé Ciss" },
  { teamCode: "SEN", number: 12, name: "Fodé Ballo-Touré" },
  { teamCode: "SEN", number: 13, name: "Iliman Ndiaye" },
  { teamCode: "SEN", number: 14, name: "Ismail Jakobs" },
  { teamCode: "SEN", number: 15, name: "Krépin Diatta" },
  { teamCode: "SEN", number: 16, name: "Alfred Gomis" },
  { teamCode: "SEN", number: 17, name: "Pape Matar Sarr" },
  { teamCode: "SEN", number: 18, name: "Ismaïla Sarr" },
  { teamCode: "SEN", number: 19, name: "Famara Diédhiou" },
  { teamCode: "SEN", number: 20, name: "Bamba Dieng" },
  { teamCode: "SEN", number: 21, name: "Youssouf Sabaly" },
  { teamCode: "SEN", number: 22, name: "Abdou Diallo" },
  { teamCode: "SEN", number: 23, name: "Seny Dieng" },
  { teamCode: "SEN", number: 24, name: "Moustapha Name" },
  { teamCode: "SEN", number: 25, name: "Mamadou Loum" },
  { teamCode: "SEN", number: 26, name: "Pape Gueye" },
  // USA — Grupo B (26)
  { teamCode: "USA", number: 1,  name: "Matt Turner" },
  { teamCode: "USA", number: 2,  name: "Sergiño Dest" },
  { teamCode: "USA", number: 3,  name: "Walker Zimmerman" },
  { teamCode: "USA", number: 4,  name: "Tyler Adams" },
  { teamCode: "USA", number: 5,  name: "Antonee Robinson" },
  { teamCode: "USA", number: 6,  name: "Yunus Musah" },
  { teamCode: "USA", number: 7,  name: "Giovanni Reyna" },
  { teamCode: "USA", number: 8,  name: "Weston McKennie" },
  { teamCode: "USA", number: 9,  name: "Jesús Ferreira" },
  { teamCode: "USA", number: 10, name: "Christian Pulisic" },
  { teamCode: "USA", number: 11, name: "Brenden Aaronson" },
  { teamCode: "USA", number: 12, name: "Ethan Horvath" },
  { teamCode: "USA", number: 13, name: "Tim Ream" },
  { teamCode: "USA", number: 14, name: "Luca de la Torre" },
  { teamCode: "USA", number: 15, name: "Aaron Long" },
  { teamCode: "USA", number: 16, name: "Jordan Morris" },
  { teamCode: "USA", number: 17, name: "Cristian Roldan" },
  { teamCode: "USA", number: 18, name: "Shaq Moore" },
  { teamCode: "USA", number: 19, name: "Haji Wright" },
  { teamCode: "USA", number: 20, name: "Cameron Carter-Vickers" },
  { teamCode: "USA", number: 21, name: "Timothy Weah" },
  { teamCode: "USA", number: 22, name: "DeAndre Yedlin" },
  { teamCode: "USA", number: 23, name: "Kellyn Acosta" },
  { teamCode: "USA", number: 24, name: "Josh Sargent" },
  { teamCode: "USA", number: 25, name: "Sean Johnson" },
  { teamCode: "USA", number: 26, name: "Joe Scally" },
  // WAL — Grupo B (26)
  { teamCode: "WAL", number: 1,  name: "Wayne Hennessey" },
  { teamCode: "WAL", number: 2,  name: "Chris Gunter" },
  { teamCode: "WAL", number: 3,  name: "Neco Williams" },
  { teamCode: "WAL", number: 4,  name: "Ben Davies" },
  { teamCode: "WAL", number: 5,  name: "Chris Mepham" },
  { teamCode: "WAL", number: 6,  name: "Joe Rodon" },
  { teamCode: "WAL", number: 7,  name: "Joe Allen" },
  { teamCode: "WAL", number: 8,  name: "Harry Wilson" },
  { teamCode: "WAL", number: 9,  name: "Brennan Johnson" },
  { teamCode: "WAL", number: 10, name: "Aaron Ramsey" },
  { teamCode: "WAL", number: 11, name: "Gareth Bale" },
  { teamCode: "WAL", number: 12, name: "Danny Ward" },
  { teamCode: "WAL", number: 13, name: "Kieffer Moore" },
  { teamCode: "WAL", number: 14, name: "Connor Roberts" },
  { teamCode: "WAL", number: 15, name: "Ethan Ampadu" },
  { teamCode: "WAL", number: 16, name: "Joe Morrell" },
  { teamCode: "WAL", number: 17, name: "Tom Lockyer" },
  { teamCode: "WAL", number: 18, name: "Jonny Williams" },
  { teamCode: "WAL", number: 19, name: "Mark Harris" },
  { teamCode: "WAL", number: 20, name: "Daniel James" },
  { teamCode: "WAL", number: 21, name: "Adam Davies" },
  { teamCode: "WAL", number: 22, name: "Sorba Thomas" },
  { teamCode: "WAL", number: 23, name: "Dylan Levitt" },
  { teamCode: "WAL", number: 24, name: "Ben Cabango" },
  { teamCode: "WAL", number: 25, name: "Rubin Colwill" },
  { teamCode: "WAL", number: 26, name: "Matthew Smith" },
  // ENG — Grupo B (26)
  { teamCode: "ENG", number: 1,  name: "Jordan Pickford" },
  { teamCode: "ENG", number: 2,  name: "Kyle Walker" },
  { teamCode: "ENG", number: 3,  name: "Luke Shaw" },
  { teamCode: "ENG", number: 4,  name: "Declan Rice" },
  { teamCode: "ENG", number: 5,  name: "John Stones" },
  { teamCode: "ENG", number: 6,  name: "Harry Maguire" },
  { teamCode: "ENG", number: 7,  name: "Jack Grealish" },
  { teamCode: "ENG", number: 8,  name: "Jordan Henderson" },
  { teamCode: "ENG", number: 9,  name: "Harry Kane" },
  { teamCode: "ENG", number: 10, name: "Raheem Sterling" },
  { teamCode: "ENG", number: 11, name: "Marcus Rashford" },
  { teamCode: "ENG", number: 12, name: "Kieran Trippier" },
  { teamCode: "ENG", number: 13, name: "Nick Pope" },
  { teamCode: "ENG", number: 14, name: "Kalvin Phillips" },
  { teamCode: "ENG", number: 15, name: "Eric Dier" },
  { teamCode: "ENG", number: 16, name: "Conor Coady" },
  { teamCode: "ENG", number: 17, name: "Bukayo Saka" },
  { teamCode: "ENG", number: 18, name: "Trent Alexander-Arnold" },
  { teamCode: "ENG", number: 19, name: "Mason Mount" },
  { teamCode: "ENG", number: 20, name: "Phil Foden" },
  { teamCode: "ENG", number: 21, name: "Ben White" },
  { teamCode: "ENG", number: 22, name: "Jude Bellingham" },
  { teamCode: "ENG", number: 23, name: "Aaron Ramsdale" },
  { teamCode: "ENG", number: 24, name: "Callum Wilson" },
  { teamCode: "ENG", number: 25, name: "James Maddison" },
  { teamCode: "ENG", number: 26, name: "Conor Gallagher" },
  // IRN — Grupo B (25, sin dorsal 26 en convocatoria oficial)
  { teamCode: "IRN", number: 1,  name: "Alireza Beiranvand" },
  { teamCode: "IRN", number: 2,  name: "Sadegh Moharrami" },
  { teamCode: "IRN", number: 3,  name: "Ehsan Hajsafi" },
  { teamCode: "IRN", number: 4,  name: "Shojae Khalilzadeh" },
  { teamCode: "IRN", number: 5,  name: "Milad Mohammadi" },
  { teamCode: "IRN", number: 6,  name: "Saeid Ezatolahi" },
  { teamCode: "IRN", number: 7,  name: "Alireza Jahanbakhsh" },
  { teamCode: "IRN", number: 8,  name: "Morteza Pouraliganji" },
  { teamCode: "IRN", number: 9,  name: "Mehdi Taremi" },
  { teamCode: "IRN", number: 10, name: "Karim Ansarifard" },
  { teamCode: "IRN", number: 11, name: "Vahid Amiri" },
  { teamCode: "IRN", number: 12, name: "Payam Niazmand" },
  { teamCode: "IRN", number: 13, name: "Hossein Kanaanizadegan" },
  { teamCode: "IRN", number: 14, name: "Saman Ghoddos" },
  { teamCode: "IRN", number: 15, name: "Rouzbeh Cheshmi" },
  { teamCode: "IRN", number: 16, name: "Mehdi Torabi" },
  { teamCode: "IRN", number: 17, name: "Ali Gholizadeh" },
  { teamCode: "IRN", number: 18, name: "Ali Karimi" },
  { teamCode: "IRN", number: 19, name: "Majid Hosseini" },
  { teamCode: "IRN", number: 20, name: "Sardar Azmoun" },
  { teamCode: "IRN", number: 21, name: "Ahmad Nourollahi" },
  { teamCode: "IRN", number: 22, name: "Amir Abedzadeh" },
  { teamCode: "IRN", number: 23, name: "Ramin Rezaeian" },
  { teamCode: "IRN", number: 24, name: "Hossein Hosseini" },
  { teamCode: "IRN", number: 25, name: "Abolfazl Jalali" },
  // KSA — Grupo C (26)
  { teamCode: "KSA", number: 1,  name: "Mohammed Al-Rubaie" },
  { teamCode: "KSA", number: 2,  name: "Sultan Al-Ghannam" },
  { teamCode: "KSA", number: 3,  name: "Abdullah Madu" },
  { teamCode: "KSA", number: 4,  name: "Abdulelah Al-Amri" },
  { teamCode: "KSA", number: 5,  name: "Ali Al-Bulaihi" },
  { teamCode: "KSA", number: 6,  name: "Mohammed Al-Breik" },
  { teamCode: "KSA", number: 7,  name: "Salman Al-Faraj" },
  { teamCode: "KSA", number: 8,  name: "Abdulellah Al-Malki" },
  { teamCode: "KSA", number: 9,  name: "Firas Al-Buraikan" },
  { teamCode: "KSA", number: 10, name: "Salem Al-Dawsari" },
  { teamCode: "KSA", number: 11, name: "Saleh Al-Shehri" },
  { teamCode: "KSA", number: 12, name: "Saud Abdulhamid" },
  { teamCode: "KSA", number: 13, name: "Yasser Al-Shahrani" },
  { teamCode: "KSA", number: 14, name: "Abdullah Otayf" },
  { teamCode: "KSA", number: 15, name: "Ali Al-Hassan" },
  { teamCode: "KSA", number: 16, name: "Sami Al-Najei" },
  { teamCode: "KSA", number: 17, name: "Hassan Al-Tambakti" },
  { teamCode: "KSA", number: 18, name: "Nawaf Al-Abed" },
  { teamCode: "KSA", number: 19, name: "Hattan Bahebri" },
  { teamCode: "KSA", number: 20, name: "Abdulrahman Al-Aboud" },
  { teamCode: "KSA", number: 21, name: "Mohammed Al-Owais" },
  { teamCode: "KSA", number: 22, name: "Nawaf Al-Aqidi" },
  { teamCode: "KSA", number: 23, name: "Mohamed Kanno" },
  { teamCode: "KSA", number: 24, name: "Nasser Al-Dawsari" },
  { teamCode: "KSA", number: 25, name: "Haitham Asiri" },
  { teamCode: "KSA", number: 26, name: "Riyadh Sharahili" },
  // ARG — Grupo C (26)
  { teamCode: "ARG", number: 1,  name: "Franco Armani" },
  { teamCode: "ARG", number: 2,  name: "Juan Foyth" },
  { teamCode: "ARG", number: 3,  name: "Nicolás Tagliafico" },
  { teamCode: "ARG", number: 4,  name: "Gonzalo Montiel" },
  { teamCode: "ARG", number: 5,  name: "Leandro Paredes" },
  { teamCode: "ARG", number: 6,  name: "Germán Pezzella" },
  { teamCode: "ARG", number: 7,  name: "Rodrigo De Paul" },
  { teamCode: "ARG", number: 8,  name: "Marcos Acuña" },
  { teamCode: "ARG", number: 9,  name: "Julián Álvarez" },
  { teamCode: "ARG", number: 10, name: "Lionel Messi" },
  { teamCode: "ARG", number: 11, name: "Ángel Di María" },
  { teamCode: "ARG", number: 12, name: "Gerónimo Rulli" },
  { teamCode: "ARG", number: 13, name: "Cristian Romero" },
  { teamCode: "ARG", number: 14, name: "Exequiel Palacios" },
  { teamCode: "ARG", number: 15, name: "Ángel Correa" },
  { teamCode: "ARG", number: 16, name: "Thiago Almada" },
  { teamCode: "ARG", number: 17, name: "Alejandro 'Papu' Gómez" },
  { teamCode: "ARG", number: 18, name: "Guido Rodríguez" },
  { teamCode: "ARG", number: 19, name: "Nicolás Otamendi" },
  { teamCode: "ARG", number: 20, name: "Alexis Mac Allister" },
  { teamCode: "ARG", number: 21, name: "Paulo Dybala" },
  { teamCode: "ARG", number: 22, name: "Lautaro Martínez" },
  { teamCode: "ARG", number: 23, name: "Emiliano Martínez" },
  { teamCode: "ARG", number: 24, name: "Enzo Fernández" },
  { teamCode: "ARG", number: 25, name: "Lisandro Martínez" },
  { teamCode: "ARG", number: 26, name: "Nahuel Molina" },
  // MEX — Grupo C (26)
  { teamCode: "MEX", number: 1,  name: "Alfredo Talavera" },
  { teamCode: "MEX", number: 2,  name: "Néstor Araujo" },
  { teamCode: "MEX", number: 3,  name: "César Montes" },
  { teamCode: "MEX", number: 4,  name: "Edson Álvarez" },
  { teamCode: "MEX", number: 5,  name: "Johan Vásquez" },
  { teamCode: "MEX", number: 6,  name: "Gerardo Arteaga" },
  { teamCode: "MEX", number: 7,  name: "Luis Romo" },
  { teamCode: "MEX", number: 8,  name: "Carlos Rodríguez" },
  { teamCode: "MEX", number: 9,  name: "Raúl Jiménez" },
  { teamCode: "MEX", number: 10, name: "Alexis Vega" },
  { teamCode: "MEX", number: 11, name: "Rogelio Funes Mori" },
  { teamCode: "MEX", number: 12, name: "Rodolfo Cota" },
  { teamCode: "MEX", number: 13, name: "Guillermo Ochoa" },
  { teamCode: "MEX", number: 14, name: "Érick Gutiérrez" },
  { teamCode: "MEX", number: 15, name: "Héctor Moreno" },
  { teamCode: "MEX", number: 16, name: "Héctor Herrera" },
  { teamCode: "MEX", number: 17, name: "Orbelín Pineda" },
  { teamCode: "MEX", number: 18, name: "Andrés Guardado" },
  { teamCode: "MEX", number: 19, name: "Jorge Sánchez" },
  { teamCode: "MEX", number: 20, name: "Henry Martín" },
  { teamCode: "MEX", number: 21, name: "Uriel Antuna" },
  { teamCode: "MEX", number: 22, name: "Hirving Lozano" },
  { teamCode: "MEX", number: 23, name: "Jesús Gallardo" },
  { teamCode: "MEX", number: 24, name: "Luis Chávez" },
  { teamCode: "MEX", number: 25, name: "Roberto Alvarado" },
  { teamCode: "MEX", number: 26, name: "Kevin Álvarez" },
  // POL — Grupo C (26)
  { teamCode: "POL", number: 1,  name: "Wojciech Szczęsny" },
  { teamCode: "POL", number: 2,  name: "Matty Cash" },
  { teamCode: "POL", number: 3,  name: "Artur Jędrzejczyk" },
  { teamCode: "POL", number: 4,  name: "Mateusz Wieteska" },
  { teamCode: "POL", number: 5,  name: "Jan Bednarek" },
  { teamCode: "POL", number: 6,  name: "Krystian Bielik" },
  { teamCode: "POL", number: 7,  name: "Arkadiusz Milik" },
  { teamCode: "POL", number: 8,  name: "Damian Szymański" },
  { teamCode: "POL", number: 9,  name: "Robert Lewandowski" },
  { teamCode: "POL", number: 10, name: "Grzegorz Krychowiak" },
  { teamCode: "POL", number: 11, name: "Kamil Grosicki" },
  { teamCode: "POL", number: 12, name: "Łukasz Skorupski" },
  { teamCode: "POL", number: 13, name: "Jakub Kamiński" },
  { teamCode: "POL", number: 14, name: "Jakub Kiwior" },
  { teamCode: "POL", number: 15, name: "Kamil Glik" },
  { teamCode: "POL", number: 16, name: "Karol Świderski" },
  { teamCode: "POL", number: 17, name: "Szymon Żurkowski" },
  { teamCode: "POL", number: 18, name: "Bartosz Bereszyński" },
  { teamCode: "POL", number: 19, name: "Sebastian Szymański" },
  { teamCode: "POL", number: 20, name: "Piotr Zieliński" },
  { teamCode: "POL", number: 21, name: "Nicola Zalewski" },
  { teamCode: "POL", number: 22, name: "Kamil Grabara" },
  { teamCode: "POL", number: 23, name: "Krzysztof Piątek" },
  { teamCode: "POL", number: 24, name: "Przemysław Frankowski" },
  { teamCode: "POL", number: 25, name: "Robert Gumny" },
  { teamCode: "POL", number: 26, name: "Michał Skóraś" },
  // AUS — Grupo D (26)
  { teamCode: "AUS", number: 1,  name: "Mathew Ryan" },
  { teamCode: "AUS", number: 2,  name: "Miloš Degenek" },
  { teamCode: "AUS", number: 3,  name: "Nathaniel Atkinson" },
  { teamCode: "AUS", number: 4,  name: "Kye Rowles" },
  { teamCode: "AUS", number: 5,  name: "Fran Karačić" },
  { teamCode: "AUS", number: 6,  name: "Marco Tilio" },
  { teamCode: "AUS", number: 7,  name: "Mathew Leckie" },
  { teamCode: "AUS", number: 8,  name: "Bailey Wright" },
  { teamCode: "AUS", number: 9,  name: "Jamie Maclaren" },
  { teamCode: "AUS", number: 10, name: "Ajdin Hrustic" },
  { teamCode: "AUS", number: 11, name: "Awer Mabil" },
  { teamCode: "AUS", number: 12, name: "Andrew Redmayne" },
  { teamCode: "AUS", number: 13, name: "Aaron Mooy" },
  { teamCode: "AUS", number: 14, name: "Riley McGree" },
  { teamCode: "AUS", number: 15, name: "Mitchell Duke" },
  { teamCode: "AUS", number: 16, name: "Aziz Behich" },
  { teamCode: "AUS", number: 17, name: "Cameron Devlin" },
  { teamCode: "AUS", number: 18, name: "Danny Vukovic" },
  { teamCode: "AUS", number: 19, name: "Harry Souttar" },
  { teamCode: "AUS", number: 20, name: "Thomas Deng" },
  { teamCode: "AUS", number: 21, name: "Garang Kuol" },
  { teamCode: "AUS", number: 22, name: "Jackson Irvine" },
  { teamCode: "AUS", number: 23, name: "Craig Goodwin" },
  { teamCode: "AUS", number: 24, name: "Joel King" },
  { teamCode: "AUS", number: 25, name: "Jason Cummings" },
  { teamCode: "AUS", number: 26, name: "Keanu Baccus" },
  // DEN — Grupo D (26)
  { teamCode: "DEN", number: 1,  name: "Kasper Schmeichel" },
  { teamCode: "DEN", number: 2,  name: "Joachim Andersen" },
  { teamCode: "DEN", number: 3,  name: "Victor Nelsson" },
  { teamCode: "DEN", number: 4,  name: "Simon Kjær" },
  { teamCode: "DEN", number: 5,  name: "Joakim Mæhle" },
  { teamCode: "DEN", number: 6,  name: "Andreas Christensen" },
  { teamCode: "DEN", number: 7,  name: "Mathias Jensen" },
  { teamCode: "DEN", number: 8,  name: "Thomas Delaney" },
  { teamCode: "DEN", number: 9,  name: "Martin Braithwaite" },
  { teamCode: "DEN", number: 10, name: "Christian Eriksen" },
  { teamCode: "DEN", number: 11, name: "Andreas Skov Olsen" },
  { teamCode: "DEN", number: 12, name: "Kasper Dolberg" },
  { teamCode: "DEN", number: 13, name: "Rasmus Kristensen" },
  { teamCode: "DEN", number: 14, name: "Mikkel Damsgaard" },
  { teamCode: "DEN", number: 15, name: "Christian Nørgaard" },
  { teamCode: "DEN", number: 16, name: "Oliver Christensen" },
  { teamCode: "DEN", number: 17, name: "Jens Stryger Larsen" },
  { teamCode: "DEN", number: 18, name: "Daniel Wass" },
  { teamCode: "DEN", number: 19, name: "Jonas Wind" },
  { teamCode: "DEN", number: 20, name: "Yussuf Poulsen" },
  { teamCode: "DEN", number: 21, name: "Andreas Cornelius" },
  { teamCode: "DEN", number: 22, name: "Frederik Rønnow" },
  { teamCode: "DEN", number: 23, name: "Pierre-Emile Højbjerg" },
  { teamCode: "DEN", number: 24, name: "Robert Skov" },
  { teamCode: "DEN", number: 25, name: "Jesper Lindstrøm" },
  { teamCode: "DEN", number: 26, name: "Alexander Bah" },
  // FRA — Grupo D (26)
  { teamCode: "FRA", number: 1,  name: "Hugo Lloris" },
  { teamCode: "FRA", number: 2,  name: "Benjamin Pavard" },
  { teamCode: "FRA", number: 3,  name: "Axel Disasi" },
  { teamCode: "FRA", number: 4,  name: "Raphaël Varane" },
  { teamCode: "FRA", number: 5,  name: "Jules Koundé" },
  { teamCode: "FRA", number: 6,  name: "Mattéo Guendouzi" },
  { teamCode: "FRA", number: 7,  name: "Antoine Griezmann" },
  { teamCode: "FRA", number: 8,  name: "Aurélien Tchouaméni" },
  { teamCode: "FRA", number: 9,  name: "Olivier Giroud" },
  { teamCode: "FRA", number: 10, name: "Kylian Mbappé" },
  { teamCode: "FRA", number: 11, name: "Ousmane Dembélé" },
  { teamCode: "FRA", number: 12, name: "Randal Kolo Muani" },
  { teamCode: "FRA", number: 13, name: "Youssouf Fofana" },
  { teamCode: "FRA", number: 14, name: "Adrien Rabiot" },
  { teamCode: "FRA", number: 15, name: "Jordan Veretout" },
  { teamCode: "FRA", number: 16, name: "Steve Mandanda" },
  { teamCode: "FRA", number: 17, name: "William Saliba" },
  { teamCode: "FRA", number: 18, name: "Dayot Upamecano" },
  { teamCode: "FRA", number: 19, name: "Karim Benzema" },
  { teamCode: "FRA", number: 20, name: "Kingsley Coman" },
  { teamCode: "FRA", number: 21, name: "Lucas Hernandez" },
  { teamCode: "FRA", number: 22, name: "Théo Hernandez" },
  { teamCode: "FRA", number: 23, name: "Alphonse Areola" },
  { teamCode: "FRA", number: 24, name: "Ibrahima Konaté" },
  { teamCode: "FRA", number: 25, name: "Eduardo Camavinga" },
  { teamCode: "FRA", number: 26, name: "Marcus Thuram" },
  // TUN — Grupo D (26)
  { teamCode: "TUN", number: 1,  name: "Aymen Mathlouthi" },
  { teamCode: "TUN", number: 2,  name: "Bilel Ifa" },
  { teamCode: "TUN", number: 3,  name: "Montassar Talbi" },
  { teamCode: "TUN", number: 4,  name: "Yassine Meriah" },
  { teamCode: "TUN", number: 5,  name: "Nader Ghandri" },
  { teamCode: "TUN", number: 6,  name: "Dylan Bronn" },
  { teamCode: "TUN", number: 7,  name: "Youssef Msakni" },
  { teamCode: "TUN", number: 8,  name: "Hannibal Mejbri" },
  { teamCode: "TUN", number: 9,  name: "Issam Jebali" },
  { teamCode: "TUN", number: 10, name: "Wahbi Khazri" },
  { teamCode: "TUN", number: 11, name: "Taha Yassine Khenissi" },
  { teamCode: "TUN", number: 12, name: "Ali Maâloul" },
  { teamCode: "TUN", number: 13, name: "Ferjani Sassi" },
  { teamCode: "TUN", number: 14, name: "Aïssa Laïdouni" },
  { teamCode: "TUN", number: 15, name: "Mohamed Ali Ben Romdhane" },
  { teamCode: "TUN", number: 16, name: "Aymen Dahmen" },
  { teamCode: "TUN", number: 17, name: "Ellyes Skhiri" },
  { teamCode: "TUN", number: 18, name: "Ghailene Chaalali" },
  { teamCode: "TUN", number: 19, name: "Seifeddine Jaziri" },
  { teamCode: "TUN", number: 20, name: "Mohamed Dräger" },
  { teamCode: "TUN", number: 21, name: "Wajdi Kechrida" },
  { teamCode: "TUN", number: 22, name: "Bechir Ben Saïd" },
  { teamCode: "TUN", number: 23, name: "Naïm Sliti" },
  { teamCode: "TUN", number: 24, name: "Ali Abdi" },
  { teamCode: "TUN", number: 25, name: "Anis Ben Slimane" },
  { teamCode: "TUN", number: 26, name: "Mouez Hassen" },
  // GER — Grupo E (26)
  { teamCode: "GER", number: 1,  name: "Manuel Neuer" },
  { teamCode: "GER", number: 2,  name: "Antonio Rüdiger" },
  { teamCode: "GER", number: 3,  name: "David Raum" },
  { teamCode: "GER", number: 4,  name: "Matthias Ginter" },
  { teamCode: "GER", number: 5,  name: "Thilo Kehrer" },
  { teamCode: "GER", number: 6,  name: "Joshua Kimmich" },
  { teamCode: "GER", number: 7,  name: "Kai Havertz" },
  { teamCode: "GER", number: 8,  name: "Leon Goretzka" },
  { teamCode: "GER", number: 9,  name: "Niclas Füllkrug" },
  { teamCode: "GER", number: 10, name: "Serge Gnabry" },
  { teamCode: "GER", number: 11, name: "Mario Götze" },
  { teamCode: "GER", number: 12, name: "Kevin Trapp" },
  { teamCode: "GER", number: 13, name: "Thomas Müller" },
  { teamCode: "GER", number: 14, name: "Jamal Musiala" },
  { teamCode: "GER", number: 15, name: "Niklas Süle" },
  { teamCode: "GER", number: 16, name: "Lukas Klostermann" },
  { teamCode: "GER", number: 17, name: "Julian Brandt" },
  { teamCode: "GER", number: 18, name: "Jonas Hofmann" },
  { teamCode: "GER", number: 19, name: "Leroy Sané" },
  { teamCode: "GER", number: 20, name: "Christian Günter" },
  { teamCode: "GER", number: 21, name: "İlkay Gündoğan" },
  { teamCode: "GER", number: 22, name: "Marc-André ter Stegen" },
  { teamCode: "GER", number: 23, name: "Nico Schlotterbeck" },
  { teamCode: "GER", number: 24, name: "Karim Adeyemi" },
  { teamCode: "GER", number: 25, name: "Armel Bella-Kotchap" },
  { teamCode: "GER", number: 26, name: "Youssoufa Moukoko" },
  // CRC — Grupo E (26)
  { teamCode: "CRC", number: 1,  name: "Keylor Navas" },
  { teamCode: "CRC", number: 2,  name: "Daniel Chacón" },
  { teamCode: "CRC", number: 3,  name: "Juan Pablo Vargas" },
  { teamCode: "CRC", number: 4,  name: "Keysher Fuller" },
  { teamCode: "CRC", number: 5,  name: "Celso Borges" },
  { teamCode: "CRC", number: 6,  name: "Óscar Duarte" },
  { teamCode: "CRC", number: 7,  name: "Anthony Contreras" },
  { teamCode: "CRC", number: 8,  name: "Bryan Oviedo" },
  { teamCode: "CRC", number: 9,  name: "Jewison Bennette" },
  { teamCode: "CRC", number: 10, name: "Bryan Ruiz" },
  { teamCode: "CRC", number: 11, name: "Johan Venegas" },
  { teamCode: "CRC", number: 12, name: "Joel Campbell" },
  { teamCode: "CRC", number: 13, name: "Gerson Torres" },
  { teamCode: "CRC", number: 14, name: "Youstin Salas" },
  { teamCode: "CRC", number: 15, name: "Francisco Calvo" },
  { teamCode: "CRC", number: 16, name: "Carlos Martínez" },
  { teamCode: "CRC", number: 17, name: "Yeltsin Tejeda" },
  { teamCode: "CRC", number: 18, name: "Esteban Alvarado" },
  { teamCode: "CRC", number: 19, name: "Kendall Waston" },
  { teamCode: "CRC", number: 20, name: "Brandon Aguilera" },
  { teamCode: "CRC", number: 21, name: "Douglas López" },
  { teamCode: "CRC", number: 22, name: "Rónald Matarrita" },
  { teamCode: "CRC", number: 23, name: "Patrick Sequeira" },
  { teamCode: "CRC", number: 24, name: "Roan Wilson" },
  { teamCode: "CRC", number: 25, name: "Anthony Hernández" },
  { teamCode: "CRC", number: 26, name: "Álvaro Zamora" },
  // ESP — Grupo E (26)
  { teamCode: "ESP", number: 1,  name: "Robert Sánchez" },
  { teamCode: "ESP", number: 2,  name: "César Azpilicueta" },
  { teamCode: "ESP", number: 3,  name: "Eric García" },
  { teamCode: "ESP", number: 4,  name: "Pau Torres" },
  { teamCode: "ESP", number: 5,  name: "Sergio Busquets" },
  { teamCode: "ESP", number: 6,  name: "Marcos Llorente" },
  { teamCode: "ESP", number: 7,  name: "Álvaro Morata" },
  { teamCode: "ESP", number: 8,  name: "Koke" },
  { teamCode: "ESP", number: 9,  name: "Gavi" },
  { teamCode: "ESP", number: 10, name: "Marco Asensio" },
  { teamCode: "ESP", number: 11, name: "Ferran Torres" },
  { teamCode: "ESP", number: 12, name: "Nico Williams" },
  { teamCode: "ESP", number: 13, name: "David Raya" },
  { teamCode: "ESP", number: 14, name: "Alejandro Balde" },
  { teamCode: "ESP", number: 15, name: "Hugo Guillamón" },
  { teamCode: "ESP", number: 16, name: "Rodri" },
  { teamCode: "ESP", number: 17, name: "Yéremy Pino" },
  { teamCode: "ESP", number: 18, name: "Jordi Alba" },
  { teamCode: "ESP", number: 19, name: "Carlos Soler" },
  { teamCode: "ESP", number: 20, name: "Dani Carvajal" },
  { teamCode: "ESP", number: 21, name: "Dani Olmo" },
  { teamCode: "ESP", number: 22, name: "Pablo Sarabia" },
  { teamCode: "ESP", number: 23, name: "Unai Simón" },
  { teamCode: "ESP", number: 24, name: "Aymeric Laporte" },
  { teamCode: "ESP", number: 25, name: "Ansu Fati" },
  { teamCode: "ESP", number: 26, name: "Pedri" },
  // JPN — Grupo E (26)
  { teamCode: "JPN", number: 1,  name: "Eiji Kawashima" },
  { teamCode: "JPN", number: 2,  name: "Miki Yamane" },
  { teamCode: "JPN", number: 3,  name: "Shōgo Taniguchi" },
  { teamCode: "JPN", number: 4,  name: "Kō Itakura" },
  { teamCode: "JPN", number: 5,  name: "Yūto Nagatomo" },
  { teamCode: "JPN", number: 6,  name: "Wataru Endō" },
  { teamCode: "JPN", number: 7,  name: "Gaku Shibasaki" },
  { teamCode: "JPN", number: 8,  name: "Ritsu Dōan" },
  { teamCode: "JPN", number: 9,  name: "Kaoru Mitoma" },
  { teamCode: "JPN", number: 10, name: "Takumi Minamino" },
  { teamCode: "JPN", number: 11, name: "Takefusa Kubo" },
  { teamCode: "JPN", number: 12, name: "Shūichi Gonda" },
  { teamCode: "JPN", number: 13, name: "Hidemasa Morita" },
  { teamCode: "JPN", number: 14, name: "Junya Itō" },
  { teamCode: "JPN", number: 15, name: "Daichi Kamada" },
  { teamCode: "JPN", number: 16, name: "Takehiro Tomiyasu" },
  { teamCode: "JPN", number: 17, name: "Ao Tanaka" },
  { teamCode: "JPN", number: 18, name: "Takuma Asano" },
  { teamCode: "JPN", number: 19, name: "Hiroki Sakai" },
  { teamCode: "JPN", number: 20, name: "Shūto Machino" },
  { teamCode: "JPN", number: 21, name: "Ayase Ueda" },
  { teamCode: "JPN", number: 22, name: "Maya Yoshida" },
  { teamCode: "JPN", number: 23, name: "Daniel Schmidt" },
  { teamCode: "JPN", number: 24, name: "Yūki Sōma" },
  { teamCode: "JPN", number: 25, name: "Daizen Maeda" },
  { teamCode: "JPN", number: 26, name: "Hiroki Itō" },
  // BEL — Grupo F (26)
  { teamCode: "BEL", number: 1,  name: "Thibaut Courtois" },
  { teamCode: "BEL", number: 2,  name: "Toby Alderweireld" },
  { teamCode: "BEL", number: 3,  name: "Arthur Theate" },
  { teamCode: "BEL", number: 4,  name: "Wout Faes" },
  { teamCode: "BEL", number: 5,  name: "Jan Vertonghen" },
  { teamCode: "BEL", number: 6,  name: "Axel Witsel" },
  { teamCode: "BEL", number: 7,  name: "Kevin De Bruyne" },
  { teamCode: "BEL", number: 8,  name: "Youri Tielemans" },
  { teamCode: "BEL", number: 9,  name: "Romelu Lukaku" },
  { teamCode: "BEL", number: 10, name: "Eden Hazard" },
  { teamCode: "BEL", number: 11, name: "Yannick Carrasco" },
  { teamCode: "BEL", number: 12, name: "Simon Mignolet" },
  { teamCode: "BEL", number: 13, name: "Koen Casteels" },
  { teamCode: "BEL", number: 14, name: "Dries Mertens" },
  { teamCode: "BEL", number: 15, name: "Thomas Meunier" },
  { teamCode: "BEL", number: 16, name: "Thorgan Hazard" },
  { teamCode: "BEL", number: 17, name: "Leandro Trossard" },
  { teamCode: "BEL", number: 18, name: "Amadou Onana" },
  { teamCode: "BEL", number: 19, name: "Leander Dendoncker" },
  { teamCode: "BEL", number: 20, name: "Hans Vanaken" },
  { teamCode: "BEL", number: 21, name: "Timothy Castagne" },
  { teamCode: "BEL", number: 22, name: "Charles De Ketelaere" },
  { teamCode: "BEL", number: 23, name: "Michy Batshuayi" },
  { teamCode: "BEL", number: 24, name: "Loïs Openda" },
  { teamCode: "BEL", number: 25, name: "Jérémy Doku" },
  { teamCode: "BEL", number: 26, name: "Zeno Debast" },
  // CAN — Grupo F (26)
  { teamCode: "CAN", number: 1,  name: "Dayne St. Clair" },
  { teamCode: "CAN", number: 2,  name: "Alistair Johnston" },
  { teamCode: "CAN", number: 3,  name: "Sam Adekugbe" },
  { teamCode: "CAN", number: 4,  name: "Kamal Miller" },
  { teamCode: "CAN", number: 5,  name: "Steven Vitória" },
  { teamCode: "CAN", number: 6,  name: "Samuel Piette" },
  { teamCode: "CAN", number: 7,  name: "Stephen Eustáquio" },
  { teamCode: "CAN", number: 8,  name: "Liam Fraser" },
  { teamCode: "CAN", number: 9,  name: "Lucas Cavallini" },
  { teamCode: "CAN", number: 10, name: "Junior Hoilett" },
  { teamCode: "CAN", number: 11, name: "Tajon Buchanan" },
  { teamCode: "CAN", number: 12, name: "Iké Ugbo" },
  { teamCode: "CAN", number: 13, name: "Atiba Hutchinson" },
  { teamCode: "CAN", number: 14, name: "Mark-Anthony Kaye" },
  { teamCode: "CAN", number: 15, name: "Ismaël Koné" },
  { teamCode: "CAN", number: 16, name: "James Pantemis" },
  { teamCode: "CAN", number: 17, name: "Cyle Larin" },
  { teamCode: "CAN", number: 18, name: "Milan Borjan" },
  { teamCode: "CAN", number: 19, name: "Alphonso Davies" },
  { teamCode: "CAN", number: 20, name: "Jonathan David" },
  { teamCode: "CAN", number: 21, name: "Jonathan Osorio" },
  { teamCode: "CAN", number: 22, name: "Richie Laryea" },
  { teamCode: "CAN", number: 23, name: "Liam Millar" },
  { teamCode: "CAN", number: 24, name: "David Wotherspoon" },
  { teamCode: "CAN", number: 25, name: "Derek Cornelius" },
  { teamCode: "CAN", number: 26, name: "Joel Waterman" },
  // MAR — Grupo F (26)
  { teamCode: "MAR", number: 1,  name: "Yassine Bounou" },
  { teamCode: "MAR", number: 2,  name: "Achraf Hakimi" },
  { teamCode: "MAR", number: 3,  name: "Noussair Mazraoui" },
  { teamCode: "MAR", number: 4,  name: "Sofyan Amrabat" },
  { teamCode: "MAR", number: 5,  name: "Nayef Aguerd" },
  { teamCode: "MAR", number: 6,  name: "Romain Saïss" },
  { teamCode: "MAR", number: 7,  name: "Hakim Ziyech" },
  { teamCode: "MAR", number: 8,  name: "Azzedine Ounahi" },
  { teamCode: "MAR", number: 9,  name: "Abderrazak Hamdallah" },
  { teamCode: "MAR", number: 10, name: "Anass Zaroury" },
  { teamCode: "MAR", number: 11, name: "Abdelhamid Sabiri" },
  { teamCode: "MAR", number: 12, name: "Munir Mohamedi" },
  { teamCode: "MAR", number: 13, name: "Ilias Chair" },
  { teamCode: "MAR", number: 14, name: "Zakaria Aboukhlal" },
  { teamCode: "MAR", number: 15, name: "Selim Amallah" },
  { teamCode: "MAR", number: 16, name: "Abde Ezzalzouli" },
  { teamCode: "MAR", number: 17, name: "Sofiane Boufal" },
  { teamCode: "MAR", number: 18, name: "Jawad El Yamiq" },
  { teamCode: "MAR", number: 19, name: "Youssef En-Nesyri" },
  { teamCode: "MAR", number: 20, name: "Achraf Dari" },
  { teamCode: "MAR", number: 21, name: "Walid Cheddira" },
  { teamCode: "MAR", number: 22, name: "Ahmed Reda Tagnaouti" },
  { teamCode: "MAR", number: 23, name: "Bilal El Khannous" },
  { teamCode: "MAR", number: 24, name: "Badr Benoun" },
  { teamCode: "MAR", number: 25, name: "Yahia Attiyat Allah" },
  { teamCode: "MAR", number: 26, name: "Yahya Jabrane" },
  // CRO — Grupo F (26)
  { teamCode: "CRO", number: 1,  name: "Dominik Livaković" },
  { teamCode: "CRO", number: 2,  name: "Josip Stanišić" },
  { teamCode: "CRO", number: 3,  name: "Borna Barišić" },
  { teamCode: "CRO", number: 4,  name: "Ivan Perišić" },
  { teamCode: "CRO", number: 5,  name: "Martin Erlić" },
  { teamCode: "CRO", number: 6,  name: "Dejan Lovren" },
  { teamCode: "CRO", number: 7,  name: "Lovro Majer" },
  { teamCode: "CRO", number: 8,  name: "Mateo Kovačić" },
  { teamCode: "CRO", number: 9,  name: "Andrej Kramarić" },
  { teamCode: "CRO", number: 10, name: "Luka Modrić" },
  { teamCode: "CRO", number: 11, name: "Marcelo Brozović" },
  { teamCode: "CRO", number: 12, name: "Ivo Grbić" },
  { teamCode: "CRO", number: 13, name: "Nikola Vlašić" },
  { teamCode: "CRO", number: 14, name: "Marko Livaja" },
  { teamCode: "CRO", number: 15, name: "Mario Pašalić" },
  { teamCode: "CRO", number: 16, name: "Bruno Petković" },
  { teamCode: "CRO", number: 17, name: "Ante Budimir" },
  { teamCode: "CRO", number: 18, name: "Mislav Oršić" },
  { teamCode: "CRO", number: 19, name: "Borna Sosa" },
  { teamCode: "CRO", number: 20, name: "Joško Gvardiol" },
  { teamCode: "CRO", number: 21, name: "Domagoj Vida" },
  { teamCode: "CRO", number: 22, name: "Josip Juranović" },
  { teamCode: "CRO", number: 23, name: "Ivica Ivušić" },
  { teamCode: "CRO", number: 24, name: "Josip Šutalo" },
  { teamCode: "CRO", number: 25, name: "Luka Sučić" },
  { teamCode: "CRO", number: 26, name: "Kristijan Jakić" },
  // BRA — Grupo G (26)
  { teamCode: "BRA", number: 1,  name: "Alisson" },
  { teamCode: "BRA", number: 2,  name: "Danilo" },
  { teamCode: "BRA", number: 3,  name: "Thiago Silva" },
  { teamCode: "BRA", number: 4,  name: "Marquinhos" },
  { teamCode: "BRA", number: 5,  name: "Casemiro" },
  { teamCode: "BRA", number: 6,  name: "Alex Sandro" },
  { teamCode: "BRA", number: 7,  name: "Lucas Paquetá" },
  { teamCode: "BRA", number: 8,  name: "Fred" },
  { teamCode: "BRA", number: 9,  name: "Richarlison" },
  { teamCode: "BRA", number: 10, name: "Neymar" },
  { teamCode: "BRA", number: 11, name: "Raphinha" },
  { teamCode: "BRA", number: 12, name: "Weverton" },
  { teamCode: "BRA", number: 13, name: "Dani Alves" },
  { teamCode: "BRA", number: 14, name: "Éder Militão" },
  { teamCode: "BRA", number: 15, name: "Fabinho" },
  { teamCode: "BRA", number: 16, name: "Alex Telles" },
  { teamCode: "BRA", number: 17, name: "Bruno Guimarães" },
  { teamCode: "BRA", number: 18, name: "Gabriel Jesus" },
  { teamCode: "BRA", number: 19, name: "Antony" },
  { teamCode: "BRA", number: 20, name: "Vinícius Júnior" },
  { teamCode: "BRA", number: 21, name: "Rodrygo" },
  { teamCode: "BRA", number: 22, name: "Éverton Ribeiro" },
  { teamCode: "BRA", number: 23, name: "Ederson" },
  { teamCode: "BRA", number: 24, name: "Bremer" },
  { teamCode: "BRA", number: 25, name: "Pedro" },
  { teamCode: "BRA", number: 26, name: "Gabriel Martinelli" },
  // CMR — Grupo G (26)
  { teamCode: "CMR", number: 1,  name: "Simon Ngapandouetnbu" },
  { teamCode: "CMR", number: 2,  name: "Jerome Ngom Mbekeli" },
  { teamCode: "CMR", number: 3,  name: "Nicolas N'Koulou" },
  { teamCode: "CMR", number: 4,  name: "Christopher Wooh" },
  { teamCode: "CMR", number: 5,  name: "Gaël Ondoua" },
  { teamCode: "CMR", number: 6,  name: "Nicolas Moumi Ngamaleu" },
  { teamCode: "CMR", number: 7,  name: "Georges-Kévin N'Koudou" },
  { teamCode: "CMR", number: 8,  name: "André-Frank Zambo Anguissa" },
  { teamCode: "CMR", number: 9,  name: "Jean-Pierre Nsame" },
  { teamCode: "CMR", number: 10, name: "Vincent Aboubakar" },
  { teamCode: "CMR", number: 11, name: "Christian Bassogog" },
  { teamCode: "CMR", number: 12, name: "Karl Toko Ekambi" },
  { teamCode: "CMR", number: 13, name: "Eric Maxim Choupo-Moting" },
  { teamCode: "CMR", number: 14, name: "Samuel Oum Gouet" },
  { teamCode: "CMR", number: 15, name: "Pierre Kunde" },
  { teamCode: "CMR", number: 16, name: "Devis Epassy" },
  { teamCode: "CMR", number: 17, name: "Olivier Mbaizo" },
  { teamCode: "CMR", number: 18, name: "Martin Hongla" },
  { teamCode: "CMR", number: 19, name: "Collins Fai" },
  { teamCode: "CMR", number: 20, name: "Bryan Mbeumo" },
  { teamCode: "CMR", number: 21, name: "Jean-Charles Castelletto" },
  { teamCode: "CMR", number: 22, name: "Olivier Ntcham" },
  { teamCode: "CMR", number: 23, name: "André Onana" },
  { teamCode: "CMR", number: 24, name: "Enzo Ebosse" },
  { teamCode: "CMR", number: 25, name: "Nouhou Tolo" },
  { teamCode: "CMR", number: 26, name: "Souaibou Marou" },
  // SRB — Grupo G (26)
  { teamCode: "SRB", number: 1,  name: "Marko Dmitrović" },
  { teamCode: "SRB", number: 2,  name: "Strahinja Pavlović" },
  { teamCode: "SRB", number: 3,  name: "Strahinja Erakovic" },
  { teamCode: "SRB", number: 4,  name: "Nikola Milenković" },
  { teamCode: "SRB", number: 5,  name: "Milos Veljković" },
  { teamCode: "SRB", number: 6,  name: "Nemanja Maksimović" },
  { teamCode: "SRB", number: 7,  name: "Nemanja Radonjić" },
  { teamCode: "SRB", number: 8,  name: "Nemanja Gudelj" },
  { teamCode: "SRB", number: 9,  name: "Aleksandar Mitrović" },
  { teamCode: "SRB", number: 10, name: "Dušan Tadić" },
  { teamCode: "SRB", number: 11, name: "Luka Jović" },
  { teamCode: "SRB", number: 12, name: "Predrag Rajković" },
  { teamCode: "SRB", number: 13, name: "Stefan Mitrović" },
  { teamCode: "SRB", number: 14, name: "Andrija Živković" },
  { teamCode: "SRB", number: 15, name: "Srđan Babić" },
  { teamCode: "SRB", number: 16, name: "Saša Lukić" },
  { teamCode: "SRB", number: 17, name: "Filip Kostić" },
  { teamCode: "SRB", number: 18, name: "Dušan Vlahović" },
  { teamCode: "SRB", number: 19, name: "Uroš Račić" },
  { teamCode: "SRB", number: 20, name: "Sergej Milinković-Savić" },
  { teamCode: "SRB", number: 21, name: "Filip Đuričić" },
  { teamCode: "SRB", number: 22, name: "Darko Lazović" },
  { teamCode: "SRB", number: 23, name: "Vanja Milinković-Savić" },
  { teamCode: "SRB", number: 24, name: "Ivan Ilić" },
  { teamCode: "SRB", number: 25, name: "Filip Mladenović" },
  { teamCode: "SRB", number: 26, name: "Marko Grujić" },
  // SUI — Grupo G (26)
  { teamCode: "SUI", number: 1,  name: "Yann Sommer" },
  { teamCode: "SUI", number: 2,  name: "Edimilson Fernandes" },
  { teamCode: "SUI", number: 3,  name: "Silvan Widmer" },
  { teamCode: "SUI", number: 4,  name: "Nico Elvedi" },
  { teamCode: "SUI", number: 5,  name: "Manuel Akanji" },
  { teamCode: "SUI", number: 6,  name: "Denis Zakaria" },
  { teamCode: "SUI", number: 7,  name: "Breel Embolo" },
  { teamCode: "SUI", number: 8,  name: "Remo Freuler" },
  { teamCode: "SUI", number: 9,  name: "Haris Seferović" },
  { teamCode: "SUI", number: 10, name: "Granit Xhaka" },
  { teamCode: "SUI", number: 11, name: "Renato Steffen" },
  { teamCode: "SUI", number: 12, name: "Jonas Omlin" },
  { teamCode: "SUI", number: 13, name: "Ricardo Rodríguez" },
  { teamCode: "SUI", number: 14, name: "Michel Aebischer" },
  { teamCode: "SUI", number: 15, name: "Djibril Sow" },
  { teamCode: "SUI", number: 16, name: "Christian Fassnacht" },
  { teamCode: "SUI", number: 17, name: "Ruben Vargas" },
  { teamCode: "SUI", number: 18, name: "Eray Cömert" },
  { teamCode: "SUI", number: 19, name: "Noah Okafor" },
  { teamCode: "SUI", number: 20, name: "Fabian Frei" },
  { teamCode: "SUI", number: 21, name: "Gregor Kobel" },
  { teamCode: "SUI", number: 22, name: "Fabian Schär" },
  { teamCode: "SUI", number: 23, name: "Xherdan Shaqiri" },
  { teamCode: "SUI", number: 24, name: "Philipp Köhn" },
  { teamCode: "SUI", number: 25, name: "Fabian Rieder" },
  { teamCode: "SUI", number: 26, name: "Ardon Jashari" },
  // KOR — Grupo H (26)
  { teamCode: "KOR", number: 1,  name: "Kim Seung-gyu" },
  { teamCode: "KOR", number: 2,  name: "Kim Moon-hwan" },
  { teamCode: "KOR", number: 3,  name: "Kim Jin-su" },
  { teamCode: "KOR", number: 4,  name: "Kim Min-jae" },
  { teamCode: "KOR", number: 5,  name: "Jung Woo-young" },
  { teamCode: "KOR", number: 6,  name: "Hwang In-beom" },
  { teamCode: "KOR", number: 7,  name: "Son Heung-min" },
  { teamCode: "KOR", number: 8,  name: "Paik Seung-ho" },
  { teamCode: "KOR", number: 9,  name: "Cho Gue-sung" },
  { teamCode: "KOR", number: 10, name: "Lee Jae-sung" },
  { teamCode: "KOR", number: 11, name: "Hwang Hee-chan" },
  { teamCode: "KOR", number: 12, name: "Song Bum-keun" },
  { teamCode: "KOR", number: 13, name: "Cho Yu-min" },
  { teamCode: "KOR", number: 14, name: "Kwon Kyung-won" },
  { teamCode: "KOR", number: 15, name: "Lee Kang-in" },
  { teamCode: "KOR", number: 16, name: "Hwang Ui-jo" },
  { teamCode: "KOR", number: 17, name: "Na Sang-ho" },
  { teamCode: "KOR", number: 18, name: "Kim Tae-hwan" },
  { teamCode: "KOR", number: 19, name: "Kim Young-gwon" },
  { teamCode: "KOR", number: 20, name: "Jeong Woo-yeong" },
  { teamCode: "KOR", number: 21, name: "Jo Hyeon-woo" },
  { teamCode: "KOR", number: 22, name: "Yoon Jong-gyu" },
  { teamCode: "KOR", number: 23, name: "Seol Young-woo" },
  { teamCode: "KOR", number: 24, name: "Son Jun-ho" },
  { teamCode: "KOR", number: 25, name: "Kwon Chang-hoon" },
  { teamCode: "KOR", number: 26, name: "Hong Chul" },
  // GHA — Grupo H (26)
  { teamCode: "GHA", number: 1,  name: "Lawrence Ati-Zigi" },
  { teamCode: "GHA", number: 2,  name: "Denis Odoi" },
  { teamCode: "GHA", number: 3,  name: "Daniel-Kofi Kyereh" },
  { teamCode: "GHA", number: 4,  name: "Mohammed Salisu" },
  { teamCode: "GHA", number: 5,  name: "Thomas Partey" },
  { teamCode: "GHA", number: 6,  name: "Salis Abdul Samed" },
  { teamCode: "GHA", number: 7,  name: "Issahaku Abdul Fatawu" },
  { teamCode: "GHA", number: 8,  name: "Daniel Amartey" },
  { teamCode: "GHA", number: 9,  name: "Antoine Semenyo" },
  { teamCode: "GHA", number: 10, name: "Andre Ayew" },
  { teamCode: "GHA", number: 11, name: "Kamaldeen Sulemana" },
  { teamCode: "GHA", number: 12, name: "Joseph Aidoo" },
  { teamCode: "GHA", number: 13, name: "Gideon Mensah" },
  { teamCode: "GHA", number: 14, name: "Jordan Ayew" },
  { teamCode: "GHA", number: 15, name: "Daniel Afriyie" },
  { teamCode: "GHA", number: 16, name: "Danlad Ibrahim" },
  { teamCode: "GHA", number: 17, name: "Baba Rahman" },
  { teamCode: "GHA", number: 18, name: "Mohammed Kudus" },
  { teamCode: "GHA", number: 19, name: "Iñaki Williams" },
  { teamCode: "GHA", number: 20, name: "Tariq Lamptey" },
  { teamCode: "GHA", number: 21, name: "Abdul Manaf Nurudeen" },
  { teamCode: "GHA", number: 22, name: "Osman Bukari" },
  { teamCode: "GHA", number: 23, name: "Alexander Djiku" },
  { teamCode: "GHA", number: 24, name: "Kamal Sowah" },
  { teamCode: "GHA", number: 25, name: "Elisha Owusu" },
  { teamCode: "GHA", number: 26, name: "Alidu Seidu" },
  // POR — Grupo H (26)
  { teamCode: "POR", number: 1,  name: "Diogo Costa" },
  { teamCode: "POR", number: 2,  name: "Nuno Mendes" },
  { teamCode: "POR", number: 3,  name: "Pepe" },
  { teamCode: "POR", number: 4,  name: "Rúben Dias" },
  { teamCode: "POR", number: 5,  name: "Raphaël Guerreiro" },
  { teamCode: "POR", number: 6,  name: "José Fonte" },
  { teamCode: "POR", number: 7,  name: "Cristiano Ronaldo" },
  { teamCode: "POR", number: 8,  name: "Bruno Fernandes" },
  { teamCode: "POR", number: 9,  name: "André Silva" },
  { teamCode: "POR", number: 10, name: "Bernardo Silva" },
  { teamCode: "POR", number: 11, name: "João Félix" },
  { teamCode: "POR", number: 12, name: "José Sá" },
  { teamCode: "POR", number: 13, name: "Danilo Pereira" },
  { teamCode: "POR", number: 14, name: "William Carvalho" },
  { teamCode: "POR", number: 15, name: "João Mário" },
  { teamCode: "POR", number: 16, name: "Rúben Neves" },
  { teamCode: "POR", number: 17, name: "Rafael Leão" },
  { teamCode: "POR", number: 18, name: "Matheus Nunes" },
  { teamCode: "POR", number: 19, name: "Ricardo Horta" },
  { teamCode: "POR", number: 20, name: "João Cancelo" },
  { teamCode: "POR", number: 21, name: "Diogo Dalot" },
  { teamCode: "POR", number: 22, name: "Rui Patrício" },
  { teamCode: "POR", number: 23, name: "António Silva" },
  { teamCode: "POR", number: 24, name: "João Palhinha" },
  { teamCode: "POR", number: 25, name: "Otávio" },
  { teamCode: "POR", number: 26, name: "Gonçalo Ramos" },
  // URU — Grupo H (26)
  { teamCode: "URU", number: 1,  name: "Fernando Muslera" },
  { teamCode: "URU", number: 2,  name: "José María Giménez" },
  { teamCode: "URU", number: 3,  name: "Sebastián Coates" },
  { teamCode: "URU", number: 4,  name: "Ronald Araújo" },
  { teamCode: "URU", number: 5,  name: "Manuel Ugarte" },
  { teamCode: "URU", number: 6,  name: "Diego Godín" },
  { teamCode: "URU", number: 7,  name: "Nicolás de la Cruz" },
  { teamCode: "URU", number: 8,  name: "Nahitan Nández" },
  { teamCode: "URU", number: 9,  name: "Luis Suárez" },
  { teamCode: "URU", number: 10, name: "Giorgian de Arrascaeta" },
  { teamCode: "URU", number: 11, name: "Darwin Núñez" },
  { teamCode: "URU", number: 12, name: "Sergio Rochet" },
  { teamCode: "URU", number: 13, name: "Guillermo Varela" },
  { teamCode: "URU", number: 14, name: "Lucas Torreira" },
  { teamCode: "URU", number: 15, name: "Federico Valverde" },
  { teamCode: "URU", number: 16, name: "Mathías Olivera" },
  { teamCode: "URU", number: 17, name: "Matías Viña" },
  { teamCode: "URU", number: 18, name: "Maxi Gómez" },
  { teamCode: "URU", number: 19, name: "Sebastián Sosa" },
  { teamCode: "URU", number: 20, name: "Facundo Torres" },
  { teamCode: "URU", number: 21, name: "Edinson Cavani" },
  { teamCode: "URU", number: 22, name: "Martín Cáceres" },
  { teamCode: "URU", number: 23, name: "Mauro Arambarri" },
  { teamCode: "URU", number: 24, name: "Agustín Canobbio" },
  { teamCode: "URU", number: 25, name: "Facundo Pellistri" },
  { teamCode: "URU", number: 26, name: "José Luis Rodríguez" },
];

// ─── Players ──────────────────────────────────────────────────────────────────

async function seedPlayers() {
  const teamRows = await prisma.team.findMany({ select: { id: true, code: true } });
  const codeToId = Object.fromEntries(teamRows.map((t) => [t.code, t.id]));

  const data = players.map(({ teamCode, number, name }) => ({
    teamId: codeToId[teamCode],
    number,
    name,
  }));

  const { count } = await prisma.player.createMany({ data, skipDuplicates: true });
  console.log(`✓ ${count} jugadores insertados.`);
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  await seedTeams();
  await seedMatches();
  await seedPlayers();
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
